hi

diff --git a/.github/actions/docker_build/action.yml b/.github/actions/docker_build/action.yml
--- a/.github/actions/docker_build/action.yml
+++ b/.github/actions/docker_build/action.yml
@@ -8,6 +8,10 @@ inputs:
   docker_image_name:
     description: "Name of the Docker image to push"
     required: true
+  dockerfile_path:
+    description: "Path to the Dockerfile"
+    required: false
+    default: "Dockerfile"
 
 runs:
   using: composite
@@ -24,6 +28,16 @@ runs:
           echo "Error: docker_image_name input cannot be empty."
           exit 1
         fi
+
+    - name: Build Docker Image
+      shell: bash
+      run: |
+        IMAGE_NAME="${{ inputs.docker_image_name }}"
+        echo "Building Docker image: $IMAGE_NAME"
+        docker build -t "$IMAGE_NAME" -f "${{ inputs.dockerfile_path }}" . || {
+          echo "Error building Docker image."
+          exit 1
+        }
 
     - name: Tag Docker Image
       shell: bash
