hi

diff --git a/.github/actions/docker_build/action.yml b/.github/actions/docker_build/action.yml
--- a/.github/actions/docker_build/action.yml
+++ b/.github/actions/docker_build/action.yml
@@ -1,45 +1,61 @@
-name: Build
-description: Build application with Maven and create a new Docker image
-inputs:
-  path_dockerfile:
-    description: "Path to the Dockerfile"
-    required: false
-    default: "./src/main/docker/Dockerfile.jvm"
-  image_name:
-    description: "Name for the Docker image"
-    required: true
-    default: "default_image_name"
-  tag_name:
-    description: "Tag for the Docker image"
-    required: false
+name: CI
 
-runs:
-  using: composite
-  steps:
-    - name: Set Docker Tag
-      shell: bash
-      run: |
-        if [ -z "${{ inputs.tag_name }}" ]; then
-          echo "TAG=$(date +%s)" >> $GITHUB_ENV
-        else
-          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
-        fi
+on:
+  push:
+    branches: main
 
-    - name: Validate Image Name
-      shell: bash
-      run: |
-        if [ -z "${{ inputs.image_name }}" ]; then
-          echo "Error: image_name input cannot be empty."
-          exit 1
-        fi
+jobs:
+  login:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Build Docker Image
-      shell: bash
-      run: |
-        NAME="${{ inputs.image_name }}:$TAG"
-        if ! docker build . --file "${{ inputs.path_dockerfile }}" --tag "$NAME"; then
-          echo "Docker build failed!"
-          exit 1
-        fi
-        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
-        docker images
+  build:
+    runs-on: ubuntu-latest
+    needs: login
+    steps:
+      - name: Set Docker Tag
+        shell: bash
+        run: |
+          if [ -z "${{ inputs.tag_name }}" ]; then
+            echo "TAG=latest" >> $GITHUB_ENV
+          else
+            echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
+          fi
+
+      - name: Validate Image Name
+        shell: bash
+        run: |
+          if [ -z "${{ inputs.image_name }}" ]; then
+            echo "Error: image_name input cannot be empty."
+            exit 1
+          fi
+
+      - name: Build Docker Image
+        shell: bash
+        run: |
+          NAME="${{ inputs.image_name }}:$TAG"
+          if ! docker build "$(dirname "${{ inputs.path_dockerfile }}")" --file "${{ inputs.path_dockerfile }}" --tag "$NAME"; then
+            echo "Docker build failed!"
+            exit 1
+          fi
+          echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
+          echo "Built Docker image: $NAME"
+          docker images
+
+      - name: Push Docker Image
+        shell: bash
+        run: |
+          NAME="${{ inputs.image_name }}:$TAG"
+          if ! docker push "$NAME"; then
+            echo "Docker push failed!"
+            exit 1
+          fi
+          echo "Successfully pushed Docker image: $NAME"
+
+      - name: Cleanup
+        run: docker system prune -f --volumes
